image:
    file: .gitpod.Dockerfile

tasks:
  - init: mvn process-test-resources

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - eamodio.gitlens
